version: "3.5"

services:

  nginx:
    image: nginx:alpine3.18
    networks:
      myNet192:
        ipv4_address: 192.168.111.2
    ports:
    - 80:80
    restart: always
    volumes:
    - /srv/www/html:/var/www/html
    - /srv/nginx/conf:/etc/nginx/conf.d
    - /srv/nginx/logs:/var/log/nginx

  php-fpm:
    build:
      context: php-fpm
    networks:
      myNet192:
        ipv4_address: 192.168.111.3
    restart: always
    volumes:
    - /srv/www/html:/var/www/html:rw

  php:
    build:
      context: php
    networks:
      myNet192:
        ipv4_address: 192.168.111.4
    ports:
    - 81:80
    restart: always
    volumes:
    - /srv/www/html:/var/www/html:rw

  mardiadb:
    image: mariadb:11.2
    networks:
      myNet192:
        ipv4_address: 192.168.111.5
    ports:
    - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: testdb
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_pass
    volumes:
    - databases_mysql:/var/lib/mysql  


  grafana:
    image: grafana/grafana:10.2.2
    networks:
      myNet192:
        ipv4_address: 192.168.111.6
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - prometheus
    volumes:
      - grafana-data:/var/lib/grafana
      - grafana-configs:/etc/grafana

  prometheus:
    image: prom/prometheus:v2.48.0
    networks:
      myNet192:
        ipv4_address: 192.168.111.7
    ports:
      - "9090:9090"
    restart: always
    volumes:
      - prom-data:/prometheus
      - prom-configs:/etc/prometheus

  node-exporter:
    image: prom/node-exporter:v1.7.0
    networks:
      myNet192:
        ipv4_address: 192.168.111.8
    ports:
      - "9100:9100"
    restart: always
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude'
      - '^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)'

# not ready
#  bitnami/nginx-exporter:0.11.0
#  fluentd:v1.16.2-1.1


  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    restart: always
    depends_on:
      - prometheus
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    expose:
      - 8080
    networks:
      myNet192:
        ipv4_address: 192.168.111.20



volumes:
  databases_mysql:
  grafana-data:
  grafana-configs:
  prom-data:
  prom-configs:

networks:
  myNet192:
    ipam:
      driver: default
      config:
        - subnet: 192.168.111.0/24
